[build-system]
requires = ["setuptools>=83", "setuptools-scm>=10"]
build-backend = "setuptools.build_meta"

[project]
name = "django-dh-map"
dynamic = ["version"]
requires-python = ">= 3.14"
dependencies = [
    # Django packages
    "Django>=6.0.3",
    "django-polymorphic>=4.11.2",
    "django-nested-admin",
    # "django-nested-admin>=4.1.6",
    # "django-nested-admin @ git+https://github.com/djmaze/django-nested-admin@fix/django-polymorphic-4.6-compatibility-improved",
    "django-jsonform>=2.23.2",
    "django-admin-interface>=0.32.0",
    "django-solo>=2.5.1",
    "django-tinymce>=5.0.0",
    "django-imagekit>=6.1.0",
    "django-ffield>=0.0.9",
    "python-magic>=0.4.27", # required by django-ffield
    "django-async-upload-kg>=4.0.5",
    "django-js-asset>=3.1.2",
    "djangorestframework>=3.17.1",
    "djangorestframework-gis>=1.2.1",
    "django-admin-sortable2>=2.3.1",
    # jobs: rq for processing
    "django-rq>=3.2.2",
    "redis>=7.4.0",
    # post processing jobs
    "pillow>=12.1.1",
    "numpy>=2.4.4",
    "py360convert>=1.0.4",
    "natsort>=8.4.0",
    # Database (psycopg[binary] cannot be locked to specific version number)
    "psycopg[binary]",
]
authors = [
  { name="Andrew Gardener", email="andrew_gardener@sfu.ca" },
]
description = "A Django app meant to help build out Digital Humanities (DH) mapping projects quickly. This is a very opinionated package that is primarily meant for in-house use only but others might find it useful as a starting point"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[project.optional-dependencies]
django-health-check = ["django-health-check>=3.20.8"]
django-cleanup = ["django-cleanup>=9.0.0"]
django-cache-cleaner = ["django-cache-cleaner>=0.2.0"]
django-vite = ["django-vite>=3.1.0"]

[project.urls]
Homepage = "https://github.com/sfu-dhil/django-dh-map"
Source = "https://github.com/sfu-dhil/django-dh-map"

[tool.setuptools_scm]
version_scheme = 'no-guess-dev'
local_scheme = 'no-local-version'

[tool.setuptools.packages.find]
include = ["django_dh_map*"]