# Generated by Django 6.0.3 on 2026-04-16 00:44

import django.db.models.deletion
import django_dh_map.fields
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Block',
                'db_table': 'django_dh_map_cb',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Item',
                'db_table': 'django_dh_map_ci',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('license', models.CharField(blank=True, null=True)),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Published?')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Map',
                'db_table': 'django_dh_map_map',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlockImage',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('name', models.CharField(blank=True, null=True)),
                ('original', django_dh_map.fields.AsyncImageFFileField(help_text='Please use a high resolution image.<br/>JPEG, PNG, WEBP, and AVIF are allowed.', max_length=255, upload_to='images/', verbose_name='High Resolution Image')),
                ('description', models.CharField(blank=True, help_text='Description of the image for accessibility.', null=True)),
                ('license', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'db_table': 'django_dh_map_cb_image',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='ContentBlockRichText',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Rich Text',
                'db_table': 'django_dh_map_cb_rich_text',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentitem')),
                ('title', models.CharField()),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Published?')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Info Page',
                'db_table': 'django_dh_map_ci_info_page',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentitem',),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='django_dh_map.contentitem'),
        ),
        migrations.CreateModel(
            name='OverheadImageMap',
            fields=[
                ('map_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.map')),
                ('image', django_dh_map.fields.AsyncImageFFileField(height_field='height', help_text='Please use a high resolution image.<br/>PNG or TIFF are recommended.<br/>JPEG, PNG, WEBP, AVIF, and TIFF are allowed.', max_length=255, upload_to='maps/', verbose_name='High Resolution Map Image', width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('tiles_dir', models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='(overhead|panorama)_.*$', max_length=255, null=True, path=pathlib.PurePosixPath('/media/maps'))),
                ('tile_size', models.IntegerField(blank=True, null=True)),
                ('tile_format', models.CharField(blank=True, choices=[('avif', 'avif'), ('webp', 'webp'), ('png', 'png')], null=True)),
                ('min_zoom', models.IntegerField(blank=True, null=True)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Overhead Image Map',
                'db_table': 'django_dh_map_overhead_map',
            },
            bases=('django_dh_map.map',),
        ),
        migrations.CreateModel(
            name='PanoramaImageMap',
            fields=[
                ('map_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.map')),
                ('image', django_dh_map.fields.AsyncImageFFileField(height_field='height', help_text='Please use a high resolution image.<br/>PNG or TIFF are recommended.<br/>JPEG, PNG, WEBP, AVIF, and TIFF are allowed.', max_length=255, upload_to='maps/', verbose_name='High Resolution Map Image', width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('tiles_dir', models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='(overhead|panorama)_.*$', max_length=255, null=True, path=pathlib.PurePosixPath('/media/maps'))),
                ('tile_size', models.IntegerField(blank=True, null=True)),
                ('tile_format', models.CharField(blank=True, choices=[('avif', 'avif'), ('webp', 'webp'), ('png', 'png')], null=True)),
                ('min_zoom', models.IntegerField(blank=True, null=True)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Panorama Image Map',
                'db_table': 'django_dh_map_panorama_map',
            },
            bases=('django_dh_map.map',),
        ),
    ]
