# Generated by Django 6.0.3 on 2026-07-20 22:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_dh_map.fields
import django_jsonform.models.fields
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Block',
                'db_table': 'django_dh_cb',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Content Item',
                'db_table': 'django_dh_ci',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Icon',
                'db_table': 'django_dh_icon',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('license', models.CharField(blank=True, null=True)),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Published?')),
                ('position', models.IntegerField(db_index=True, default=0)),
                ('data_srid', models.PositiveIntegerField(choices=[(0, 'Flat, Cartesian coordinate system (SRID 0)'), (4326, 'World Geodetic System (WGS84 / SRID 4326)'), (3857, 'Web Mercator (SRID 3857)')], default=4326, verbose_name='GeoJson Projection Spacial Reference Identifier (SRID)')),
                ('feature_srid', models.PositiveIntegerField(choices=[(0, 'Flat, Cartesian coordinate system (SRID 0)'), (4326, 'World Geodetic System (WGS84 / SRID 4326)'), (3857, 'Web Mercator (SRID 3857)')], default=3857, verbose_name='Map Projection Spacial Reference Identifier (SRID)')),
                ('properties', models.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Map',
                'db_table': 'django_dh_map',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='MapGeoJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_geojson', to='django_dh_map.map')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'GeoJson',
                'db_table': 'django_dh_geojson',
            },
        ),
        migrations.CreateModel(
            name='ContentBlockAudio',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('name', models.CharField(blank=True, null=True)),
                ('original', django_dh_map.fields.AsyncFFileField(help_text='Please use a high quality audio.', max_length=255, upload_to='audio/', verbose_name='High Quality Audio')),
                ('audio_dir', models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='audio_.*$', max_length=255, null=True, path=pathlib.PurePosixPath('/media/audio'))),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('license', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio',
                'db_table': 'django_dh_cb_audio',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='ContentBlockImage',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('name', models.CharField(blank=True, null=True)),
                ('original', django_dh_map.fields.ImageFFileField(help_text='Please use a high resolution image.<br/>JPEG, PNG, WEBP, and AVIF are allowed.', max_length=255, upload_to='images/', verbose_name='High Resolution Image')),
                ('description', models.CharField(blank=True, help_text='Description of the image for accessibility.', null=True)),
                ('license', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'db_table': 'django_dh_cb_image',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='ContentBlockImageBeforeAndAfter',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('caption', models.CharField(blank=True, help_text='Caption for the before and after images.', null=True)),
                ('before_name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('before_original', django_dh_map.fields.ImageFFileField(help_text='Please use a high resolution image.<br/>JPEG, PNG, WEBP, and AVIF are allowed.', max_length=255, upload_to='images/', verbose_name='High Resolution Image')),
                ('before_description', models.CharField(blank=True, help_text='Description of the image for accessibility.', null=True, verbose_name='Description')),
                ('before_license', models.CharField(blank=True, null=True, verbose_name='License')),
                ('after_name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('after_original', django_dh_map.fields.ImageFFileField(help_text='Please use a high resolution image.<br/>JPEG, PNG, WEBP, and AVIF are allowed.', max_length=255, upload_to='images/', verbose_name='High Resolution Image')),
                ('after_description', models.CharField(blank=True, help_text='Description of the image for accessibility.', null=True, verbose_name='Description')),
                ('after_license', models.CharField(blank=True, null=True, verbose_name='License')),
            ],
            options={
                'verbose_name': 'Image Before & After',
                'db_table': 'django_dh_cb_image_before_and_after',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='ContentBlockImageGallery',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
            ],
            options={
                'verbose_name': 'Image Gallery',
                'db_table': 'django_dh_cb_image_gallery',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='ContentBlockRichText',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Rich Text',
                'db_table': 'django_dh_cb_rich_text',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='ContentBlockVideo',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('name', models.CharField(blank=True, null=True)),
                ('original', django_dh_map.fields.AsyncFFileField(help_text='Please use a high resolution video.', max_length=255, upload_to='videos/', verbose_name='High Resolution Video')),
                ('video_dir', models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='video_.*$', max_length=255, null=True, path=pathlib.PurePosixPath('/media/videos'))),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('thumbnails_vtt', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('license', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'db_table': 'django_dh_cb_video',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentitem')),
                ('title', models.CharField()),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Published?')),
                ('properties', django_jsonform.models.fields.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'db_table': 'django_dh_ci_feature',
            },
            bases=('django_dh_map.contentitem',),
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentitem')),
                ('title', models.CharField()),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Published?')),
                ('position', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Info Page',
                'db_table': 'django_dh_ci_info_page',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentitem',),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='django_dh_map.contentitem'),
        ),
        migrations.CreateModel(
            name='IconImage',
            fields=[
                ('icon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.icon')),
                ('original', django_dh_map.fields.ImageFFileField(help_text='Please use a high resolution image.<br/>JPEG, PNG, WEBP, and AVIF are allowed.', max_length=255, upload_to='images/', verbose_name='High Resolution Image')),
            ],
            options={
                'verbose_name': 'Image Icon',
                'db_table': 'django_dh_icon_image',
            },
            bases=('django_dh_map.icon',),
        ),
        migrations.CreateModel(
            name='IconNumbered',
            fields=[
                ('icon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.icon')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Numbered Icon',
                'db_table': 'django_dh_icon_numbered',
            },
            bases=('django_dh_map.icon',),
        ),
        migrations.CreateModel(
            name='OverheadImageMap',
            fields=[
                ('map_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.map')),
                ('image', django_dh_map.fields.ImageFFileField(height_field='height', help_text='Please use a high resolution image.<br/>PNG or TIFF are recommended.<br/>JPEG, PNG, WEBP, AVIF, and TIFF are allowed.', max_length=255, upload_to='maps/', verbose_name='High Resolution Map Image', width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('tiles_dir', models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='(overhead|panorama)_.*$', max_length=255, null=True, path=pathlib.PurePosixPath('/media/maps'))),
                ('tile_size', models.IntegerField(blank=True, null=True)),
                ('tile_format', models.CharField(blank=True, choices=[('avif', 'avif'), ('webp', 'webp'), ('png', 'png')], null=True)),
                ('min_zoom', models.IntegerField(blank=True, null=True)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Overhead Image Map',
                'db_table': 'django_dh_map_overhead',
            },
            bases=('django_dh_map.map',),
        ),
        migrations.CreateModel(
            name='PanoramaImageMap',
            fields=[
                ('map_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.map')),
                ('image', django_dh_map.fields.ImageFFileField(height_field='height', help_text='Please use a high resolution image.<br/>PNG or TIFF are recommended.<br/>JPEG, PNG, WEBP, AVIF, and TIFF are allowed.', max_length=255, upload_to='maps/', verbose_name='High Resolution Map Image', width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('tiles_dir', models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='(overhead|panorama)_.*$', max_length=255, null=True, path=pathlib.PurePosixPath('/media/maps'))),
                ('tile_size', models.IntegerField(blank=True, null=True)),
                ('tile_format', models.CharField(blank=True, choices=[('avif', 'avif'), ('webp', 'webp'), ('png', 'png')], null=True)),
                ('min_zoom', models.IntegerField(blank=True, null=True)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
                ('cube_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Panorama Image Map',
                'db_table': 'django_dh_map_panorama',
            },
            bases=('django_dh_map.map',),
        ),
        migrations.CreateModel(
            name='XyzMap',
            fields=[
                ('map_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.map')),
                ('url', models.CharField()),
                ('min_zoom', models.IntegerField(blank=True, null=True)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
                ('attributions', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'XYZ Map',
                'db_table': 'django_dh_map_xyz',
            },
            bases=('django_dh_map.map',),
        ),
        migrations.CreateModel(
            name='MapGeoJsonLabel',
            fields=[
                ('mapgeojson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.mapgeojson')),
                ('label', models.TextField()),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'GeoJson Label',
                'db_table': 'django_dh_geojson_label',
            },
            bases=('django_dh_map.mapgeojson',),
        ),
        migrations.CreateModel(
            name='ContentBlockImageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(db_index=True, default=0)),
                ('name', models.CharField(blank=True, null=True)),
                ('original', django_dh_map.fields.ImageFFileField(help_text='Please use a high resolution image.<br/>JPEG, PNG, WEBP, and AVIF are allowed.', max_length=255, upload_to='images/', verbose_name='High Resolution Image')),
                ('description', models.CharField(blank=True, help_text='Description of the image for accessibility.', null=True)),
                ('license', models.CharField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='django_dh_map.contentblockimagegallery')),
            ],
            options={
                'verbose_name': 'Image Gallery Image',
                'db_table': 'django_dh_cb_image_gallery_image',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='icon',
            name='feature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='django_dh_map.feature'),
        ),
        migrations.CreateModel(
            name='MapGeoJsonFeature',
            fields=[
                ('mapgeojson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.mapgeojson')),
                ('geom_points', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_geojson', to='django_dh_map.feature')),
            ],
            options={
                'verbose_name': 'GeoJson Feature',
                'db_table': 'django_dh_geojson_feature',
            },
            bases=('django_dh_map.mapgeojson',),
        ),
        migrations.AddField(
            model_name='feature',
            name='maps',
            field=models.ManyToManyField(related_name='features', through='django_dh_map.MapGeoJsonFeature', to='django_dh_map.map'),
        ),
        migrations.CreateModel(
            name='MapGeoJsonTransition',
            fields=[
                ('mapgeojson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.mapgeojson')),
                ('geom_points', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('destination_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_map_geojson_transition', to='django_dh_map.map')),
            ],
            options={
                'verbose_name': 'GeoJson Transition',
                'db_table': 'django_dh_geojson_transition',
            },
            bases=('django_dh_map.mapgeojson',),
        ),
        migrations.AddField(
            model_name='map',
            name='map_transitions',
            field=models.ManyToManyField(through='django_dh_map.MapGeoJsonTransition', to='django_dh_map.map'),
        ),
    ]
