# Generated by Django 6.0.8 on 2026-09-03 17:52

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dh_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='properties',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
