# Generated by Django 6.0.3 on 2026-04-20 19:48

import django.db.models.deletion
import django_dh_map.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dh_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlockImageBeforeAndAfter',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('before_name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('before_original', django_dh_map.fields.AsyncImageFFileField(help_text='Please use a high resolution image.<br/>JPEG, PNG, WEBP, and AVIF are allowed.', max_length=255, upload_to='images/', verbose_name='High Resolution Image')),
                ('before_description', models.CharField(blank=True, help_text='Description of the image for accessibility.', null=True, verbose_name='Description')),
                ('before_license', models.CharField(blank=True, null=True, verbose_name='License')),
                ('after_name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('after_original', django_dh_map.fields.AsyncImageFFileField(help_text='Please use a high resolution image.<br/>JPEG, PNG, WEBP, and AVIF are allowed.', max_length=255, upload_to='images/', verbose_name='High Resolution Image')),
                ('after_description', models.CharField(blank=True, help_text='Description of the image for accessibility.', null=True, verbose_name='Description')),
                ('after_license', models.CharField(blank=True, null=True, verbose_name='License')),
            ],
            options={
                'verbose_name': 'Image Before & After',
                'db_table': 'django_dh_map_cb_image_before_and_after',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='ContentBlockImageGallery',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
            ],
            options={
                'verbose_name': 'Image Gallery',
                'db_table': 'django_dh_map_cb_image_gallery',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.CreateModel(
            name='ContentBlockImageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(blank=True, null=True)),
                ('original', django_dh_map.fields.AsyncImageFFileField(help_text='Please use a high resolution image.<br/>JPEG, PNG, WEBP, and AVIF are allowed.', max_length=255, upload_to='images/', verbose_name='High Resolution Image')),
                ('description', models.CharField(blank=True, help_text='Description of the image for accessibility.', null=True)),
                ('license', models.CharField(blank=True, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='django_dh_map.contentblockimagegallery')),
            ],
            options={
                'verbose_name': 'Image Gallery Image',
                'db_table': 'django_dh_map_cb_image_gallery_image',
                'ordering': ['position'],
            },
        ),
    ]
