# Generated by Django 6.0.3 on 2026-04-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dh_map', '0002_contentblockimagebeforeandafter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Content Block'},
        ),
    ]
