# Generated by Django 6.0.3 on 2026-04-20 23:29

import django.db.models.deletion
import django_dh_map.fields
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dh_map', '0003_alter_contentblock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlockVideo',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('name', models.CharField(blank=True, null=True)),
                ('original', django_dh_map.fields.AsyncFFileField(help_text='Please use a high resolution video.', max_length=255, upload_to='videos/', verbose_name='High Resolution Video')),
                ('video_dir', models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='video_.*$', max_length=255, null=True, path=pathlib.PurePosixPath('/media/videos'))),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('thumbnails_vtt', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('description', models.CharField(blank=True, help_text='Description of the video for accessibility.', null=True)),
                ('license', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'db_table': 'django_dh_map_cb_video',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
    ]
