# Generated by Django 6.0.3 on 2026-04-21 20:26

import django.db.models.deletion
import django_dh_map.fields
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dh_map', '0004_contentblockvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlockAudio',
            fields=[
                ('contentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentblock')),
                ('name', models.CharField(blank=True, null=True)),
                ('original', django_dh_map.fields.AsyncFFileField(help_text='Please use a high quality audio.', max_length=255, upload_to='videos/', verbose_name='High Quality Audio')),
                ('audio_dir', models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='audio_.*$', max_length=255, null=True, path=pathlib.PurePosixPath('/media/audio'))),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('license', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audio',
                'db_table': 'django_dh_map_cb_audio',
                'ordering': ['position'],
            },
            bases=('django_dh_map.contentblock',),
        ),
        migrations.RemoveField(
            model_name='contentblockvideo',
            name='description',
        ),
    ]
