# Generated by Django 6.0.3 on 2026-04-21 20:31

import django_dh_map.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dh_map', '0005_contentblockaudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblockaudio',
            name='original',
            field=django_dh_map.fields.AsyncFFileField(help_text='Please use a high quality audio.', max_length=255, upload_to='audio/', verbose_name='High Quality Audio'),
        ),
    ]
