# Generated by Django 6.0.3 on 2026-04-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dh_map', '0006_alter_contentblockaudio_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblockaudio',
            options={'ordering': ['position'], 'verbose_name': 'Audio', 'verbose_name_plural': 'Audio'},
        ),
        migrations.AddField(
            model_name='panoramaimagemap',
            name='cube_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
