# Generated by Django 6.0.3 on 2026-07-27 23:06

import django.db.models.deletion
import django_dh_map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_dh_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome')),
                ('display', models.BooleanField(db_index=True, default=False, verbose_name='Display?')),
                ('close_button_label', models.CharField(default='Close')),
            ],
            options={
                'verbose_name': 'Welcome Modal',
                'db_table': 'example_app_welcome_modal',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Example App')),
                ('first_button_label', models.CharField(default='View Map', verbose_name='First Button Label')),
                ('second_button_label', models.CharField(default='View Panorama', verbose_name='Second Button Label')),
                ('first_button_map', models.ForeignKey(limit_choices_to=models.Q(('published', True)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_first_button', to='django_dh_map.map', verbose_name='First Button Map')),
                ('second_button_map', models.ForeignKey(limit_choices_to=models.Q(('published', True)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_second_button', to='django_dh_map.panoramaimagemap', verbose_name='Second Button Map')),
            ],
            options={
                'verbose_name': 'Home Page',
                'db_table': 'example_app_home_page',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentitem')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_item', to='example_app.homepage')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'db_table': 'example_app_ci_home_page',
            },
            bases=('django_dh_map.contentitem',),
        ),
        migrations.CreateModel(
            name='WelcomeModalContent',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_dh_map.contentitem')),
                ('welcome_modal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_item', to='example_app.welcomemodal')),
            ],
            options={
                'verbose_name': 'Welcome Modal Content',
                'db_table': 'example_app_ci_welcome_modal',
            },
            bases=('django_dh_map.contentitem',),
        ),
    ]
